# Generated by Django 4.2.29 on 2026-03-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes visible only to agents/admins.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending Customer'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('ai_category', models.CharField(blank=True, choices=[('BILLING', 'Billing'), ('TECH_SUPPORT', 'Technical Support'), ('BUG', 'Bug Report'), ('FEATURE', 'Feature Request'), ('GENERAL', 'General Inquiry'), ('OTHER', 'Other')], help_text='Predicted ticket category from the NLP classifier.', max_length=15, null=True)),
                ('ai_sentiment', models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative / Urgent')], help_text='Predicted sentiment from the NLP sentiment analyser.', max_length=10, null=True)),
                ('ai_sentiment_score', models.FloatField(blank=True, help_text='Confidence score (0–1) of the sentiment prediction.', null=True)),
                ('ai_suggested_reply', models.TextField(blank=True, help_text='LLM-generated draft reply for the agent.')),
                ('ai_processed', models.BooleanField(default=False, help_text='Set to True once the Celery AI task has completed.')),
                ('first_response_at', models.DateTimeField(blank=True, help_text='Timestamp of the first agent/admin message on this ticket.', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when the ticket status changed to RESOLVED.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
